run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 12m

issues:
  exclude-dirs:
    - testdata$
    - test/mock
  exclude-files:
    - ".*\\.pb\\.go$"
  exclude-rules:
    - linters: [ gosec ]
      path: "(.*_test\\.go$)|(^test/.*)"
      text: "integer overflow conversion"

linters:
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - errorlint
    - gocritic
    - gofmt
    - goimports
    - gosec
    - intrange
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - revive
    - unconvert
    - unparam
    - wastedassign
    - whitespace

linters-settings:
  govet:
    enable:
      - nilness
      - sortslice
      - unusedwrite
  revive:
    # minimal confidence for issues, default is 0.8
    confidence: 0.0
    rules:
      - name: unused-parameter
        disabled: true
